Fix getrandom fallback
If sys/random.h cannot be found, the build terminates with this error:

pihole-ftl-6.5/src/config/password.c: In function ‘get_secure_randomness’:
pihole-ftl-6.5/src/config/password.c:100:52: error: ‘GRND_NONBLOCK’ undeclared (first use in this function); did you mean ‘SOCK_NONBLOCK’?
  100 |                 result = getrandom(buffer, length, GRND_NONBLOCK);
      |                                                    ^~~~~~~~~~~~~
      |                                                    SOCK_NONBLOCK

Add the missing definition of GRND_NONBLOCK in daemon.h.

Signed-off-by: Andreas Ziegler <15275159+aeolio@users.noreply.github.com>