Fix build with missing execinfo.h
The __GLIBC__ logic to detect stack backtracing capability fails for
uClibc, because uClibc also defines these symbols, but backtrace
functionality is optional.

pihole-ftl-6.5/src/signals.c:13:10: fatal error: execinfo.h: No such file or directory
   13 | #include <execinfo.h>
      |          ^~~~~~~~~~~~

Instead of adding unreadable preprocessor exceptions, have CMake detect
execinfo.h and use a appropriate preprocessor symbol.

Signed-off-by: Andreas Ziegler <15275159+aeolio@users.noreply.github.com>