Fix build without mbedtls:
Commit 3b45213 (Implement automatic TLS/SSL certificate renewals) [1]
introduced functionality that requires mbedtls, but mbedtls is an
optional dependency. This leads to the following compilation error:

pihole-ftl-6.5/src/webserver/webserver.c:36:10: fatal error: mbedtls/ssl_ciphersuites.h: No such file or directory
   36 | #include <mbedtls/ssl_ciphersuites.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Use the HAVE_MBEDTLS preprocessor symbol to assert that certificate related
code is only included if mbedtls is present in the build.

[1] https://github.com/pi-hole/FTL/commit/3b45213

Signed-off-by: Andreas Ziegler <15275159+aeolio@users.noreply.github.com>